spring:
  application: 
    name: mystream-user
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema-h2.sql
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:my_stream_user;MODE=MYSQL"
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 33665

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: mystream-user
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.JsonSerializer
